environment: development

logging:
  file:
    name: logs/se452-dev.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework: ERROR
    edu.group10.se452_g10: DEBUG

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:devDB
  sql:
    init:
      platform: h2
      mode: always






